spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/alkfet-cert-store
  autoconfigure:
    exclude:
      - de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration


