server {
}
    }
        proxy_pass http://alkfet-api-svc:8080/;
    location /api/ {

    }
        try_files $uri $uri/ /index.html;
    location / {

    index index.html;
    root /usr/share/nginx/html;
    server_name localhost;
    listen 80;

